### ISSUE TITLE
how to gen train data?

### ISSUE THREAD

**Issue by FantDing** [HotaekHan/SSTDNet#4]
How to prepare training data? After I run `python3 datagen.py`, errors happens
```python
Traceback (most recent call last):
  File "datagen.py", line 540, in <module>
    test()
  File "datagen.py", line 531, in test
    for images, loc_targets, cls_targets, mask_targets in dataloader:
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 310, in __iter__
    return DataLoaderIter(self)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 180, in __init__
    self._put_indices()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 219, in _put_indices
    indices = next(self.sample_iter, None)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/sampler.py", line 119, in __iter__
    for idx in self.sampler:
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/sampler.py", line 50, in __iter__
    return iter(torch.randperm(len(self.data_source)).long())
RuntimeError: invalid argument 1: must be strictly positive at /pytorch/torch/lib/TH/generic/THTensorMath.c:2184
```
Thanks!

**Comment by HotaekHan** [comment]
hm.....well, It looks there are no data file in the path.
could you tell me how set the paramter for 'ListDataset' class?
